name = "glate"
version = "0.1.0"

description = "A Gleam library for compiled templates, either during compile-time or runtime."
licences = ["Apache-2.0"]
repository = { type = "github", user = "nootr", repo = "glate" }
links = [{ title = "Website", href = "https://github.com/nootr/glate" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
